# This file was generated by GoReleaser. DO NOT EDIT.
cask "envdesk" do
  name "envdesk"
  desc "Local-first CLI for managing encrypted env files across services and environments"
  homepage "https://github.com/mhiro2/envdesk"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envdesk"

  on_macos do
    on_intel do
      url "https://github.com/mhiro2/envdesk/releases/download/v#{version}/envdesk_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/envdesk/"
      sha256 "6c4f304518429ef30b34770c8e826996a137aa7731d8d2636e3fa6a224298fee"
    end
    on_arm do
      url "https://github.com/mhiro2/envdesk/releases/download/v#{version}/envdesk_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/envdesk/"
      sha256 "dfe52e3fd423ea2ed69baee1fd6cb7ba7f8952811c21b2c9bb95016c81667ddd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mhiro2/envdesk/releases/download/v#{version}/envdesk_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mhiro2/envdesk/"
      sha256 "0b81309b4116675a81c3b01ad29b84da9504bf2588ac0661f94457bbf133d15a"
    end
    on_arm do
      url "https://github.com/mhiro2/envdesk/releases/download/v#{version}/envdesk_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mhiro2/envdesk/"
      sha256 "bc3406b8c1312b4c339bdfee08aea671326978a3e22c737466f79cb28c6d868e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envdesk"]
    end
  end

  # No zap stanza required
end
