# This file is generated by .github/workflows/brew-bump.yaml. DO NOT EDIT.
cask "nagori" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "c7894e42108fe4085c0333aec0344290fb6d7c549c1023f9cc75f1e41d3ab298"
      url "https://github.com/mhiro2/nagori/releases/download/v#{version}/Nagori_#{version}_aarch64.dmg",
        verified: "github.com/mhiro2/nagori/"
    end
    on_intel do
      sha256 "d311ea3fba4edcfa5cf58b03bac070bff6bdb625b66ed443ee1d3c9bfe2a74f9"
      url "https://github.com/mhiro2/nagori/releases/download/v#{version}/Nagori_#{version}_x64.dmg",
        verified: "github.com/mhiro2/nagori/"
    end
  end

  name "Nagori"
  desc "Local-first, AI-assisted clipboard manager"
  homepage "https://github.com/mhiro2/nagori"

  livecheck do
    skip "Auto-generated on release."
  end

  app "Nagori.app"
  # Link the CLI bundled inside the .app onto Homebrew's PATH so the
  # nagori command works from a terminal without the in-app installer.
  binary "#{appdir}/Nagori.app/Contents/MacOS/nagori"

  zap trash: [
    "~/Library/Application Support/nagori",
    "~/Library/Application Support/io.github.mhiro2.nagori",
    "~/Library/Caches/io.github.mhiro2.nagori",
    "~/Library/Logs/io.github.mhiro2.nagori",
    "~/Library/Preferences/io.github.mhiro2.nagori.plist",
  ]
end
