# This file is generated by .github/workflows/brew-bump.yaml. DO NOT EDIT.
cask "nagori" do
  version "0.1.2"

  sha256 "4ecacea7b0dd1f8ddd042578df029f80243c0c242ceb6c497357e9d17057b3e0"
  url "https://github.com/mhiro2/nagori/releases/download/v#{version}/Nagori_#{version}_aarch64.dmg",
    verified: "github.com/mhiro2/nagori/"

  name "Nagori"
  desc "Local-first, AI-assisted clipboard manager"
  homepage "https://github.com/mhiro2/nagori"

  # Apple Silicon only. Stated explicitly so Homebrew refuses the
  # install on an Intel Mac with an arch message instead of
  # downloading an arm64 bundle that cannot launch.
  depends_on arch: :arm64

  livecheck do
    skip "Auto-generated on release."
  end

  app "Nagori.app"
  # Link the CLI bundled inside the .app onto Homebrew's PATH so the
  # nagori command works from a terminal without the in-app installer.
  binary "#{appdir}/Nagori.app/Contents/MacOS/nagori"

  zap trash: [
    "~/Library/Application Support/nagori",
    "~/Library/Application Support/io.github.mhiro2.nagori",
    "~/Library/Caches/io.github.mhiro2.nagori",
    "~/Library/Logs/io.github.mhiro2.nagori",
    "~/Library/Preferences/io.github.mhiro2.nagori.plist",
  ]
end
