# This file is generated by .github/workflows/brew-bump.yaml. DO NOT EDIT.
cask "nagori" do
  version "0.1.3"
  sha256 "077f9be6cb7edd24d7f0fb580c94bfecdcbe79b50999bce335b516fc7870eee6"

  url "https://github.com/mhiro2/nagori/releases/download/v#{version}/Nagori_#{version}_aarch64.dmg"
  name "Nagori"
  desc "Local-first, AI-assisted clipboard manager"
  homepage "https://github.com/mhiro2/nagori"

  livecheck do
    skip "Auto-generated on release."
  end

  # Apple Silicon only. Stated explicitly so Homebrew refuses the
  # install on an Intel Mac with an arch message instead of
  # downloading an arm64 bundle that cannot launch.
  depends_on arch: :arm64
  depends_on :macos

  app "Nagori.app"
  # Link the CLI bundled inside the .app onto Homebrew's PATH so the
  # nagori command works from a terminal without the in-app installer.
  binary "#{appdir}/Nagori.app/Contents/MacOS/nagori"

  zap trash: [
    "~/Library/Application Support/io.github.mhiro2.nagori",
    "~/Library/Application Support/nagori",
    "~/Library/Caches/io.github.mhiro2.nagori",
    "~/Library/Logs/io.github.mhiro2.nagori",
    "~/Library/Preferences/io.github.mhiro2.nagori.plist",
  ]
end
