# This file was generated by GoReleaser. DO NOT EDIT.
cask "relune" do
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/mhiro2/relune/releases/download/v#{version}/relune_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/relune/"
      sha256 "3fc8936c4e693778852c52b35e0b47e4d6c0549a7631cba309cb1d0442887214"
    end
    on_arm do
      url "https://github.com/mhiro2/relune/releases/download/v#{version}/relune_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/relune/"
      sha256 "69fdfcac3002b0362e7c553d0ab6a61d6dc09a9e0782543d7ee9c86d896d04fc"
    end
  end

  name "relune"
  desc "Schema visualization and analysis for developers"
  homepage "https://github.com/mhiro2/relune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relune"]
    end
  end

  # No zap stanza required

end
