# This file was generated by GoReleaser. DO NOT EDIT.
cask "relune" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "ebe34e4b63c9cb24cd506e0266bce55f28b7e80b256374be04eb0ea88da71f1a"
      url "https://github.com/mhiro2/relune/releases/download/v#{version}/relune_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/relune/"
    end
    on_arm do
      sha256 "4483a34f6b3f251e0d63267e47f0465f1f0782b29eb1c6124507927b00489e87"
      url "https://github.com/mhiro2/relune/releases/download/v#{version}/relune_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/relune/"
    end
  end

  name "relune"
  desc "Schema visualization and analysis for developers"
  homepage "https://github.com/mhiro2/relune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relune"]
    end
  end

  # No zap stanza required

end
