# This file was generated by GoReleaser. DO NOT EDIT.
cask "relune" do
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/mhiro2/relune/releases/download/v#{version}/relune_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/relune/"
      sha256 "c5c0301d2bae7e2766094e38ca10a381fa3374f392d23dc9e885aa49af92e910"
    end
    on_arm do
      url "https://github.com/mhiro2/relune/releases/download/v#{version}/relune_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/relune/"
      sha256 "e3f79512f5e3a587855689fdc2a6759175c0fb53a3c0690fa4eca5d15fd16af5"
    end
  end

  name "relune"
  desc "Schema visualization and analysis for developers"
  homepage "https://github.com/mhiro2/relune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "relune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/relune"]
    end
  end

  # No zap stanza required

end
