# This file was generated by GoReleaser. DO NOT EDIT.
cask "seedling-gen" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "c28be0edb3b719d869c0c8e397d544050cafd2c331fa384a43123e8a40d957ed"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
    on_arm do
      sha256 "426b8addc6bd7dbde08dcc0f409a8492fa88cdf5e0419d0d7699bb35655bfc11"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ee5aef57685266f2f51519702c929d2d07b67ec8caa7fbccde72459ecd6f078"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_linux_amd64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
    on_arm do
      sha256 "89ad39c7ef69df50e5ed4f67f63a9cfe2b3dadd9405e485e10d492d5b5ef9d58"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_linux_arm64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
  end

  name "seedling-gen"
  desc "Dependency-aware test data builder CLI for Go and SQL databases"
  homepage "https://github.com/mhiro2/seedling"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seedling-gen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedling-gen"]
    end
  end

  # No zap stanza required

end
