# This file was generated by GoReleaser. DO NOT EDIT.
cask "seedling-gen" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "599c4ea4693a4156ed1a283859952009ab318e20249f37ceb81d84b56fb7ecd6"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
    on_arm do
      sha256 "a6d2184a3b9d5d31f48b0d97bcf29ff4e861c7b50c198407e456ad5fe0b54241"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
  end

  on_linux do
    on_intel do
      sha256 "27fe193f6a74ecfba311010be04a660ee945194c0feae8a41946901c55fc54e4"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_linux_amd64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
    on_arm do
      sha256 "96b5b0dff572c764f1f6047595e0b1e6540c130d976dd7a3b71847662000e008"
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_linux_arm64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
    end
  end

  name "seedling-gen"
  desc "Dependency-aware test data builder CLI for Go and SQL databases"
  homepage "https://github.com/mhiro2/seedling"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seedling-gen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedling-gen"]
    end
  end

  # No zap stanza required

end
