# This file was generated by GoReleaser. DO NOT EDIT.
cask "seedling-gen" do
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_darwin_amd64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
      sha256 "02a9c5e5b25547aaef37e9b08e189233947f7b37c76f0e408281cab78e11aa9e"
    end
    on_arm do
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_darwin_arm64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
      sha256 "1447027e390f4aacbd47b5e51abaab3233856ea34e4af4d6506989328eec4193"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_linux_amd64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
      sha256 "b0ece53463a24d2847afe2bdc2a65f2e9e9f4cbfceb571e076ebb0dc65b1db46"
    end
    on_arm do
      url "https://github.com/mhiro2/seedling/releases/download/v#{version}/seedling-gen_linux_arm64.tar.gz",
        verified: "github.com/mhiro2/seedling/"
      sha256 "c09da258fafe5732378006576f9d6bdd4d2f50d0b9f57523657a2824950309bc"
    end
  end

  name "seedling-gen"
  desc "Dependency-aware test data builder CLI for Go and SQL databases"
  homepage "https://github.com/mhiro2/seedling"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seedling-gen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seedling-gen"]
    end
  end

  # No zap stanza required

end
